##########################################################################
##                                                                      ##
##   BOOM 2 Engine                                                      ##
##                                                                      ##
##   MAKEFILE - make file for MS-DOS version                            ##
##   requires Watcom C++ 11.0 and Watcom Assembler                      ##
##                                                                      ##
##   by Ivaylo Beltchev                                                 ##
##   e-mail: ivob@geocities.com                                         ##
##   www:    www.geocities.com/SiliconValley/Bay/2234                   ##
##                                                                      ##
##########################################################################

CONFIG = release
OUTDIR = build.dos\$(CONFIG)

# compiler_options = -mf -5r -s -otlranmi -fp5 -zp1 -zdp -w2 -e20 -q -i=..\engine
compiler_options = -onatx -oh -oi -ei -zp1 -5 -fp5 -mf -s -w2 -q -i=..\engine

!ifeqi CONFIG debug
compiler_options += -d2
!endif

object_files = &
  boomdos.obj &
  kbd.obj &
  timer.obj &
  mouse.obj &
  dos4gw.obj &
  vbe20.obj &
  grtext.obj &
  collide.obj &
  draw.obj &
  geom.obj &
  player.obj &
  read.obj &
  tclip.obj &
  tcluster.obj &
  thole.obj &
  tline.obj &
  tmap.obj &
  tmapitem.obj &
  tportal.obj &
  tsector.obj &
  ttexture.obj &
  ttrap.obj &
  twall.obj &
  write.obj

.BEFORE
  @if not exist build.dos mkdir build.dos
  @if not exist $(OUTDIR) mkdir $(OUTDIR)

boomdos.exe: $(OUTDIR)\boomdos.exe .SYMBOLIC
  @%null

$(OUTDIR)\boomdos.exe : $(object_files)
  *wlink &
    option quiet &
!ifeqi CONFIG debug
    debug all &
!endif
    option eliminate &
    system dos4g &
    option stack=32768 &
    path $(OUTDIR) &
    name $^@ &
    file { $(object_files) }

.obj: $(OUTDIR)
.c: .
.cpp: .;..\engine

.c.obj: .AUTODEPEND
  *wcc386 $(compiler_options) -za99 -fo=$(OUTDIR)\$^. -fr=$(OUTDIR)\$^& $<

.cpp.obj: .AUTODEPEND
  *wpp386 $(compiler_options) -fo=$(OUTDIR)\$^. -fr=$(OUTDIR)\$^& $<

.asm.obj: .AUTODEPEND
  *wasm -i=..\engine -q -fo=$(OUTDIR)\$^. -fr=$(OUTDIR)\$^& $<

clean: .SYMBOLIC
  @if exist $(OUTDIR)\*.err del $(OUTDIR)\*.err
  @if exist $(OUTDIR)\*.obj del $(OUTDIR)\*.obj
  @if exist $(OUTDIR)\*.map del $(OUTDIR)\*.map
  @if exist $(OUTDIR)\*.exe del $(OUTDIR)\*.exe
